baseURL = "https://mushr.io/"
languageCode = "en-us"
title = "MuSHR: The UW Open Racecar Project"
theme = "hugo-serif-theme"

# Highlighting config (Pygments)
# It is (currently) not in use, but you can do ```go in a content file if you want to.
pygmentsCodeFences = true

pygmentsOptions = ""
# Use the Chroma stylesheet
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClassic = false

[markup.goldmark.renderer]
unsafe = true

[params]
  google_analytics_id="UA-146151202-1"

  [params.homepage_meta_tags]
    meta_description = "The Multi-agent System for non-Holonomic Racing (MuSHR) is an open-source robotic hardware and software platform for learning and researching AI in a the setting of autonomous vehicles and mobile robotics."
    meta_og_title = "MuSHR: The UW Open Racecar Project"
    meta_og_type = "website"
    meta_og_url = "https://prl-mushr.github.io"
    meta_og_image = "https://prl-mushr.github.io/imgs/single-car.jpg"
    meta_og_description = "The Multi-agent System for non-Holonomic Racing (MuSHR) is an open-source robotic hardware and software platform for learning and researching AI in a the setting of autonomous vehicles and mobile robotics."
    meta_twitter_card = "summary"
    meta_twitter_site = "@MichaloveJohan"
    meta_twitter_creator = "@MichaloveJohan"

# Main Menu
[[menu.main]]
    identifier = "quickstart"
	name = "Quickstart"
	url = "/tutorials/quickstart/"
    weight = 1

[[menu.main]]
    identifier = "about"
	name = "About"
	url = "/about/"
	weight = 2

[[menu.main]]
    identifier = "tutorials"
	name = "Tutorials"
	url = "/tutorials/"
    weight = 2

[[menu.main]]
    name = "Docs"
    url = "https://github.com/prl-mushr/mushr#component-documentation"
    weight = 2

[[menu.main]]
    identifier = "hardware"
    name = "Hardware"
    url = "/hardware/"
    weight = 2

[[menu.main]]
    identifier = "press"
	name = "Press"
	url = "/press/"
	weight = 3

[[menu.main]]
    identifier = "team"
    name = "Team"
    url = "https://personalrobotics.cs.washington.edu/people/"
    weight = 4

#[[menu.main]]
    #identifier = "forum"
    #name = "Forum"
    #url = "/forum/"
    #weight = 7

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 8

# Footer Menu
[[menu.footer]]
	name = "Home"
	url = "/"
    weight = 1

#[[menu.footer]]
    #identifier = "forum"
	#name = "Forum"
	#url = "/forum/"
    #weight = 2

[[menu.footer]]
    identifier = "contact"
	name = "Contact"
	url = "/contact/"
    weight = 3

[[menu.footer]]
	name = "Newsletter"
	url = "https://tinyletter.com/mushr"
    weight = 4
