baseURL = "https://mushr.io/"
languageCode = "en-us"
title = "MuSHR: The UW Open Racecar Project"
theme = "hugo-serif-theme"

# Highlighting config (Pygments)
# It is (currently) not in use, but you can do ```go in a content file if you want to.
pygmentsCodeFences = true

pygmentsOptions = ""
# Use the Chroma stylesheet
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClassic = false

[markup.goldmark.renderer]
unsafe = true

[params]
  google_analytics_id="UA-146151202-1"

  [params.homepage_meta_tags]
    meta_description = "The Multi-agent System for non-Holonomic Racing (MuSHR) is an open-source robotic hardware and software platform for learning and researching AI in a the setting of autonomous vehicles and mobile robotics."
    meta_og_title = "MuSHR: The UW Open Racecar Project"
    meta_og_type = "website"
    meta_og_url = "https://prl-mushr.github.io"
    meta_og_image = "https://prl-mushr.github.io/imgs/single-car.jpg"
    meta_og_description = "The Multi-agent System for non-Holonomic Racing (MuSHR) is an open-source robotic hardware and software platform for learning and researching AI in a the setting of autonomous vehicles and mobile robotics."
    meta_twitter_card = "summary"
    meta_twitter_site = "@MichaloveJohan"
    meta_twitter_creator = "@MichaloveJohan"

# Main Menu
[[menu.main]]
    identifier = "quickstart"
    name = "Quickstart"
    pageRef = "tutorials/quickstart"
    weight = 1

[[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "about"
    weight = 2

[[menu.main]]
    identifier = "docs"
    name = "Docs"
    url = "https://github.com/prl-mushr/mushr#component-documentation"
    weight = 3

[[menu.main]]
    identifier = "hardware"
    name = "Hardware"
    pageRef = "hardware"
    weight = 4

[[menu.main]]
    identifier = "tutorials"
    name = "Tutorials"
    pageRef = "tutorials"
    weight = 5

[[menu.main]]
    identifier = "press"
    name = "Press"
    pageRef = "press"
    weight = 6

[[menu.main]]
    identifier = "team"
    name = "Team"
    url = "https://personalrobotics.cs.washington.edu/people/"
    weight = 7

[[menu.main]]
    identifier = "forum"
    name = "Community Forum"
    url = "https://github.com/prl-mushr/mushr/discussions"
    weight = 8

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    pageRef = "contact"
    weight = 9

# Footer Menu
[[menu.footer]]
    identifier = "home"
    name = "Home"
    pageRef = "/"

[[menu.footer]]
    identifier = "forum"
    name = "Community Forum"
    url = "https://github.com/prl-mushr/mushr/discussions"

[[menu.footer]]
    identifier = "contact"
    name = "Contact"
    pageRef = "contact"
